
document.getElementById('banner');
document.getElementById('paragraphChange');


function changeText1(){
 document.getElementById("headerChange").innerHTML = "Lorem Ipsum Dolor";
 document.getElementById("paragraphChange").innerHTML = "Sweet roll gummies sweet roll tiramisu gummi bears dragée apple pie muffin. Cake toffee soufflé bear claw macaroon wafer cake biscuit. Lollipop danish chocolate cake. Cotton candy macaroon bear claw pie.Cake liquorice sesame snaps cookie pastry. Croissant danish cookie dessert chupa chups macaroon fruitcake. Marshmallow donut apple pie macaroon powder sugar plum sugar plum jelly lollipop. Chupa chups gummi bears apple pie dessert gummi bears. Marshmallow cupcake tootsie roll donut cheesecake. Fruitcake marzipan sugar plum powder tart gingerbread apple pie. Jujubes cake cheesecake candy canes halvah cookie powder tiramisu. Topping powder gummies soufflé.Magna quisque tellus mi ut vitae felis, lectus ut fusce ut nunc faucibus praesent, amet etiam sed venenatis venenatis faucibus ligula. Sagittis mauris nibh eget faucibus in venenatis, sodales sem fusce convallis hac vulputate, fringilla magna enim suspendisse sem etiam, consectetuer aliquam egestas erat ut pellentesque ac, luctus enim eu vestibulum senectus morbi volutpat. Mauris aliquam dictum pede tincidunt ac eu, non vel magna eu lacinia vestibulum, dui tellus adipiscing amet aliquet enim magna, torquent sagittis quia varius accumsan est diam. In condimentum ac quis libero veritatis dignissim, vitae quis arcu elit maecenas et libero, turpis viverra id diam suspendisse hendrerit sollicitudin, eget nascetur nullam imperdiet nisl tortor wisi, commodo in pede massa est blandit. Faucibus id urna etiam mauris eu magna, ac duis vitae scelerisque amet et sit, amet nisl dui convallis ante lectus. Risus mauris donec et velit magna faucibus, natoque lacus nec tempus mi mi, risus eget omnis aliquam nunc vitae, eu pede mauris orci mollis et, quisque sit accumsan donec neque justo. Eget praesent ligula ut eget sociosqu, scelerisque fugiat wisi mauris sed wisi, vivamus cras aliquam eros vitae dolor, sit iure porttitor turpis diam hendrerit pede, ea sapien nisl tincidunt eget molestie morbi.";

banner.style.background = '#333333';
paragraphChange.style.color = '#EAEAEA';
}
function changeText2(){
 document.getElementById("headerChange").innerHTML = "Lorem Lorem Lorem";
 document.getElementById("paragraphChange").innerHTML = "Danish chocolate bar halvah chocolate bar. Sweet roll ice cream cake liquorice cake oat cake. Muffin bonbon brownie chocolate cake jujubes bonbon. Fruitcake oat cake pudding.Cake liquorice sesame snaps cookie pastry. Croissant danish cookie dessert chupa chups macaroon fruitcake. Marshmallow donut apple pie macaroon powder sugar plum sugar plum jelly lollipop. Chupa chups gummi bears apple pie dessert gummi bears. Marshmallow cupcake tootsie roll donut cheesecake. Fruitcake marzipan sugar plum powder tart gingerbread apple pie. Jujubes cake cheesecake candy canes halvah cookie powder tiramisu. Topping powder gummies soufflé.Pede commodo ac quisque condimentum elit, suscipit integer at nulla rhoncus lacus, vel sodales metus sagittis sed neque ac, amet quis porttitor vel sodales risus id, proin quam diam faucibus ornare vivamus. Sagittis pellentesque proin mattis pulvinar posuere ac, dictumst lacinia ipsum amet elementum gravida, vestibulum class duis etiam tempor et, ornare pulvinar vitae ligula id orci, donec ut ad imperdiet at eget vestibulum. Volutpat nibh quam turpis nec sollicitudin lectus, nunc ac sed et erat pellentesque, placerat turpis gravida aliquet itaque maecenas, dolor integer id aenean euismod urna et. Dignissim pharetra tempor sed mus neque, nunc nisl in sed elementum urna, sit nullam ac ante orci vivamus, orci eu non et ornare ac per. Ante laoreet nulla vitae nulla massa pulvinar, tempor suspendisse eu neque sagittis enim hendrerit, pede proin cum elit et nulla cras. Quam at elit lectus arcu arcu augue, commodo et ut purus ipsum tellus nibh, nibh pellentesque luctus velit ultrices molestie pretium, orci eleifend iaculis nihil ac dictum. Felis in id vestibulum hendrerit consectetuer duis, facilisi faucibus nonummy turpis eleifend lacinia integer, rutrum enim magnis dapibus est morbi donec. Suspendisse et diam ut diam ligula auctor, velit curae inceptos erat et mi urna, vitae consequuntur volutpat consectetuer donec tristique non, vivamus eget wisi elit enim non integer. Imperdiet quis nam consectetuer massa pede eleifend, integer nec tortor sunt ante sed, quis aenean erat odio erat non, a arcu quis non et vestibulum. Velit sit at dui eget conubia eros, mauris integer cras urna ut ultricies, mattis a lacinia nam vel id vitae.";

 banner.style.background = '#298EE7';
 paragraphChange.style.color = '#222222';
}
function changeText3(){
 document.getElementById("headerChange").innerHTML = "Ipsum Ipsum Ipsum";
 document.getElementById("paragraphChange").innerHTML = "Chocolate bar gummies candy. Powder gummies tiramisu gummies gummies macaroon brownie marzipan donut. Chocolate bar topping pudding donut tart jelly beans topping toffee. Carrot cake dessert sugar plum.Cake liquorice sesame snaps cookie pastry. Croissant danish cookie dessert chupa chups macaroon fruitcake. Marshmallow donut apple pie macaroon powder sugar plum sugar plum jelly lollipop. Chupa chups gummi bears apple pie dessert gummi bears. Marshmallow cupcake tootsie roll donut cheesecake. Fruitcake marzipan sugar plum powder tart gingerbread apple pie. Jujubes cake cheesecake candy canes halvah cookie powder tiramisu. Topping powder gummies soufflé.Pede commodo ac quisque condimentum elit, suscipit integer at nulla rhoncus lacus, vel sodales metus sagittis sed neque ac, amet quis porttitor vel sodales risus id, proin quam diam faucibus ornare vivamus. Sagittis pellentesque proin mattis pulvinar posuere ac, dictumst lacinia ipsum amet elementum gravida, vestibulum class duis etiam tempor et, ornare pulvinar vitae ligula id orci, donec ut ad imperdiet at eget vestibulum. Volutpat nibh quam turpis nec sollicitudin lectus, nunc ac sed et erat pellentesque, placerat turpis gravida aliquet itaque maecenas, dolor integer id aenean euismod urna et. Dignissim pharetra tempor sed mus neque, nunc nisl in sed elementum urna, sit nullam ac ante orci vivamus, orci eu non et ornare ac per. Ante laoreet nulla vitae nulla massa pulvinar, tempor suspendisse eu neque sagittis enim hendrerit, pede proin cum elit et nulla cras. Quam at elit lectus arcu arcu augue, commodo et ut purus ipsum tellus nibh, nibh pellentesque luctus velit ultrices molestie pretium, orci eleifend iaculis nihil ac dictum. Felis in id vestibulum hendrerit consectetuer duis, facilisi faucibus nonummy turpis eleifend lacinia integer, rutrum enim magnis dapibus est morbi donec. Suspendisse et diam ut diam ligula auctor, velit curae inceptos erat et mi urna, vitae consequuntur volutpat consectetuer donec tristique non, vivamus eget wisi elit enim non integer. Imperdiet quis nam consectetuer massa pede eleifend, integer nec tortor sunt ante sed, quis aenean erat odio erat non, a arcu quis non et vestibulum. Velit sit at dui eget conubia eros, mauris integer cras urna ut ultricies, mattis a lacinia nam vel id vitae.";



 banner.style.background = '#FF7300';
paragraphChange.style.color = '#444444';
}
function changeText4(){
 document.getElementById("headerChange").innerHTML = "Dolor Dolor Dolor";
 document.getElementById("paragraphChange").innerHTML = "Powder sesame snaps jelly beans macaroon macaroon. Gingerbread sweet pudding cake cookie. Lemon drops sweet topping candy canes chupa chups brownie muffin. Cake liquorice sesame snaps cookie pastry. Croissant danish cookie dessert chupa chups macaroon fruitcake. Marshmallow donut apple pie macaroon powder sugar plum sugar plum jelly lollipop. Chupa chups gummi bears apple pie dessert gummi bears. Marshmallow cupcake tootsie roll donut cheesecake. Fruitcake marzipan sugar plum powder tart gingerbread apple pie. Jujubes cake cheesecake candy canes halvah cookie powder tiramisu. Topping powder gummies soufflé.Pede commodo ac quisque condimentum elit, suscipit integer at nulla rhoncus lacus, vel sodales metus sagittis sed neque ac, amet quis porttitor vel sodales risus id, proin quam diam faucibus ornare vivamus. Sagittis pellentesque proin mattis pulvinar posuere ac, dictumst lacinia ipsum amet elementum gravida, vestibulum class duis etiam tempor et, ornare pulvinar vitae ligula id orci, donec ut ad imperdiet at eget vestibulum. Volutpat nibh quam turpis nec sollicitudin lectus, nunc ac sed et erat pellentesque, placerat turpis gravida aliquet itaque maecenas, dolor integer id aenean euismod urna et. Dignissim pharetra tempor sed mus neque, nunc nisl in sed elementum urna, sit nullam ac ante orci vivamus, orci eu non et ornare ac per. Ante laoreet nulla vitae nulla massa pulvinar, tempor suspendisse eu neque sagittis enim hendrerit, pede proin cum elit et nulla cras. Quam at elit lectus arcu arcu augue, commodo et ut purus ipsum tellus nibh, nibh pellentesque luctus velit ultrices molestie pretium, orci eleifend iaculis nihil ac dictum. Felis in id vestibulum hendrerit consectetuer duis, facilisi faucibus nonummy turpis eleifend lacinia integer, rutrum enim magnis dapibus est morbi donec. Suspendisse et diam ut diam ligula auctor, velit curae inceptos erat et mi urna, vitae consequuntur volutpat consectetuer donec tristique non, vivamus eget wisi elit enim non integer. Imperdiet quis nam consectetuer massa pede eleifend, integer nec tortor sunt ante sed, quis aenean erat odio erat non, a arcu quis non et vestibulum. Velit sit at dui eget conubia eros, mauris integer cras urna ut ultricies, mattis a lacinia nam vel id vitae.";



 banner.style.background = '#AE40DA';
}
function changeText5(){
 document.getElementById("headerChange").innerHTML = "Magna Magna Magna";
 document.getElementById("paragraphChange").innerHTML = "Pie carrot cake brownie. Cheesecake dragée sweet soufflé cotton candy chupa chups lemon drops liquorice. Croissant carrot cake pastry.Cake liquorice sesame snaps cookie pastry. Croissant danish cookie dessert chupa chups macaroon fruitcake. Marshmallow donut apple pie macaroon powder sugar plum sugar plum jelly lollipop. Chupa chups gummi bears apple pie dessert gummi bears. Marshmallow cupcake tootsie roll donut cheesecake. Fruitcake marzipan sugar plum powder tart gingerbread apple pie. Jujubes cake cheesecake candy canes halvah cookie powder tiramisu. Topping powder gummies soufflé.Pede commodo ac quisque condimentum elit, suscipit integer at nulla rhoncus lacus, vel sodales metus sagittis sed neque ac, amet quis porttitor vel sodales risus id, proin quam diam faucibus ornare vivamus. Sagittis pellentesque proin mattis pulvinar posuere ac, dictumst lacinia ipsum amet elementum gravida, vestibulum class duis etiam tempor et, ornare pulvinar vitae ligula id orci, donec ut ad imperdiet at eget vestibulum. Volutpat nibh quam turpis nec sollicitudin lectus, nunc ac sed et erat pellentesque, placerat turpis gravida aliquet itaque maecenas, dolor integer id aenean euismod urna et. Dignissim pharetra tempor sed mus neque, nunc nisl in sed elementum urna, sit nullam ac ante orci vivamus, orci eu non et ornare ac per. Ante laoreet nulla vitae nulla massa pulvinar, tempor suspendisse eu neque sagittis enim hendrerit, pede proin cum elit et nulla cras. Quam at elit lectus arcu arcu augue, commodo et ut purus ipsum tellus nibh, nibh pellentesque luctus velit ultrices molestie pretium, orci eleifend iaculis nihil ac dictum. Felis in id vestibulum hendrerit consectetuer duis, facilisi faucibus nonummy turpis eleifend lacinia integer, rutrum enim magnis dapibus est morbi donec. Suspendisse et diam ut diam ligula auctor, velit curae inceptos erat et mi urna, vitae consequuntur volutpat consectetuer donec tristique non, vivamus eget wisi elit enim non integer. Imperdiet quis nam consectetuer massa pede eleifend, integer nec tortor sunt ante sed, quis aenean erat odio erat non, a arcu quis non et vestibulum. Velit sit at dui eget conubia eros, mauris integer cras urna ut ultricies, mattis a lacinia nam vel id vitae.";



 banner.style.background = '#E23B3B';
 paragraph.style.color = '#222222';
}
function changeText6(){
 document.getElementById("headerChange").innerHTML = "Etiam Etiam Etiam";
 document.getElementById("paragraphChange").innerHTML = "Cotton candy biscuit halvah. Biscuit cotton candy brownie wafer halvah fruitcake bear claw halvah. Cookie tootsie roll chupa chups pudding. Cake liquorice sesame snaps cookie pastry. Croissant danish cookie dessert chupa chups macaroon fruitcake. Marshmallow donut apple pie macaroon powder sugar plum sugar plum jelly lollipop. Chupa chups gummi bears apple pie dessert gummi bears. Marshmallow cupcake tootsie roll donut cheesecake. Fruitcake marzipan sugar plum powder tart gingerbread apple pie. Jujubes cake cheesecake candy canes halvah cookie powder tiramisu. Topping powder gummies soufflé.";

 banner.style.background = '#41BC1D';
 paragraph.style.color = '#444444';
}
